/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ethereum_sistema;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Fredy Salvador
 */
public class Ethereum_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ethereum_Principal
     */
    public Ethereum_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmaestros = new javax.swing.JDialog();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxNombreM = new javax.swing.JTextField();
        TxNumCuentaM = new javax.swing.JTextField();
        TxContraseñaM = new javax.swing.JTextField();
        TxNacionalidadM = new javax.swing.JTextField();
        TxTituloM = new javax.swing.JTextField();
        TListaClases = new javax.swing.JTextField();
        btagregarMaestro = new javax.swing.JButton();
        jalumnos = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxNombreA = new javax.swing.JTextField();
        TxNumCuentaA = new javax.swing.JTextField();
        TxContraseñaA = new javax.swing.JTextField();
        TxCarreraA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxBecadoA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TDescuentoA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btagregar2Alumno = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TListaClaseA = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TxIndiceA = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TxClaseAporbadaA = new javax.swing.JTextField();
        jAsignaturas = new javax.swing.JDialog();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxNombreAsign = new javax.swing.JTextField();
        TxNumCuentaAsign = new javax.swing.JTextField();
        TxDocenteAsign = new javax.swing.JTextField();
        TxValorUnidAsign = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxAulaAsign = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxEdificioAsign = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btagregar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TxNumSeccionAsign = new javax.swing.JTextField();
        TxHorarioAsign = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TCantalumnoAsign = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TModalidadAsign = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        TDiasImparteAsign = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        TPrecioAsign = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        MenuSelectivo = new javax.swing.JDialog();
        tmaestrocreacion = new javax.swing.JButton();
        talumnocreacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jmaestros.setPreferredSize(new java.awt.Dimension(500, 416));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Formulario de Maestros");
        jLayeredPane2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 442, 89));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jLayeredPane2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 134, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Numero de Cuenta:");
        jLayeredPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, 166, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Contraseña:");
        jLayeredPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 134, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nacional:");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 206, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Titulo:");
        jLayeredPane2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Lista de Clases:");
        jLayeredPane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));
        jLayeredPane2.add(TxNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 113, 201, -1));
        jLayeredPane2.add(TxNumCuentaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 147, 201, -1));
        jLayeredPane2.add(TxContraseñaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 175, 201, -1));
        jLayeredPane2.add(TxNacionalidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 209, 201, -1));
        jLayeredPane2.add(TxTituloM, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 237, 201, -1));
        jLayeredPane2.add(TListaClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 271, 201, -1));

        btagregarMaestro.setText("Agregar");
        btagregarMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btagregarMaestroMouseClicked(evt);
            }
        });
        jLayeredPane2.add(btagregarMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, 128, 67));

        javax.swing.GroupLayout jmaestrosLayout = new javax.swing.GroupLayout(jmaestros.getContentPane());
        jmaestros.getContentPane().setLayout(jmaestrosLayout);
        jmaestrosLayout.setHorizontalGroup(
            jmaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmaestrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jmaestrosLayout.setVerticalGroup(
            jmaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmaestrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jalumnos.setPreferredSize(new java.awt.Dimension(530, 600));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Becado:");
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Descuento");
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, -1, -1));
        jLayeredPane1.add(TxNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 107, 201, -1));
        jLayeredPane1.add(TxNumCuentaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 141, 201, -1));
        jLayeredPane1.add(TxContraseñaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 169, 201, -1));
        jLayeredPane1.add(TxCarreraA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 203, 201, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setText("Formulario de Alumnos");
        jLayeredPane1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 442, 89));
        jLayeredPane1.add(TxBecadoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 231, 201, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Nombre:");
        jLayeredPane1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, 134, -1));
        jLayeredPane1.add(TDescuentoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 265, 201, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Numero de Cuenta:");
        jLayeredPane1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, 166, -1));

        btagregar2Alumno.setText("Agregar");
        btagregar2Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btagregar2AlumnoMouseClicked(evt);
            }
        });
        jLayeredPane1.add(btagregar2Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 398, 128, 65));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Contraseña:");
        jLayeredPane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 134, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Carrera Estudia:");
        jLayeredPane1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, -1, -1));
        jLayeredPane1.add(TListaClaseA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 364, 201, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Indice Actual:");
        jLayeredPane1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Lista de Clases:");
        jLayeredPane1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 361, -1, -1));
        jLayeredPane1.add(TxIndiceA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 299, 201, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Clases Aprobadas:");
        jLayeredPane1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 330, -1, -1));

        TxClaseAporbadaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxClaseAporbadaAActionPerformed(evt);
            }
        });
        jLayeredPane1.add(TxClaseAporbadaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 330, 201, -1));

        javax.swing.GroupLayout jalumnosLayout = new javax.swing.GroupLayout(jalumnos.getContentPane());
        jalumnos.getContentPane().setLayout(jalumnosLayout);
        jalumnosLayout.setHorizontalGroup(
            jalumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jalumnosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jalumnosLayout.setVerticalGroup(
            jalumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jalumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jAsignaturas.setPreferredSize(new java.awt.Dimension(700, 1000));

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Aula:");
        jLayeredPane3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 289, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Edificios:");
        jLayeredPane3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, -1, -1));
        jLayeredPane3.add(TxNombreAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 101, 201, -1));
        jLayeredPane3.add(TxNumCuentaAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 135, 201, -1));
        jLayeredPane3.add(TxDocenteAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 227, 201, -1));

        TxValorUnidAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxValorUnidAsignActionPerformed(evt);
            }
        });
        jLayeredPane3.add(TxValorUnidAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 261, 201, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Formulario de Asignaturas");
        jLayeredPane3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 477, 89));

        TxAulaAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxAulaAsignActionPerformed(evt);
            }
        });
        jLayeredPane3.add(TxAulaAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 289, 201, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Nombre:");
        jLayeredPane3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 134, -1));
        jLayeredPane3.add(TxEdificioAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 323, 201, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Numero de Asignatura:");
        jLayeredPane3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, 193, -1));

        btagregar1.setText("Agregar");
        btagregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btagregar1MouseClicked(evt);
            }
        });
        jLayeredPane3.add(btagregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 484, 168, 66));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Docente:");
        jLayeredPane3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 227, 134, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Valor de Unidad:");
        jLayeredPane3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 258, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Numero de Seccion:");
        jLayeredPane3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 163, 166, -1));
        jLayeredPane3.add(TxNumSeccionAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 167, 201, -1));
        jLayeredPane3.add(TxHorarioAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 199, 201, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Horario:");
        jLayeredPane3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 195, 134, -1));
        jLayeredPane3.add(TCantalumnoAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 354, 201, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Cantidad Alumnos:");
        jLayeredPane3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 350, -1, -1));
        jLayeredPane3.add(TModalidadAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 386, 201, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Modalidad:");
        jLayeredPane3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 382, -1, -1));
        jLayeredPane3.add(TDiasImparteAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 418, 201, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("Dias que se Imparte:");
        jLayeredPane3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 414, -1, -1));

        TPrecioAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPrecioAsignActionPerformed(evt);
            }
        });
        jLayeredPane3.add(TPrecioAsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 450, 201, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Precio:");
        jLayeredPane3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 446, -1, -1));

        javax.swing.GroupLayout jAsignaturasLayout = new javax.swing.GroupLayout(jAsignaturas.getContentPane());
        jAsignaturas.getContentPane().setLayout(jAsignaturasLayout);
        jAsignaturasLayout.setHorizontalGroup(
            jAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAsignaturasLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jAsignaturasLayout.setVerticalGroup(
            jAsignaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAsignaturasLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tmaestrocreacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tmaestrocreacion.setText("Maestro");
        tmaestrocreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmaestrocreacionMouseClicked(evt);
            }
        });

        talumnocreacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        talumnocreacion.setText("Alumno");
        talumnocreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                talumnocreacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuSelectivoLayout = new javax.swing.GroupLayout(MenuSelectivo.getContentPane());
        MenuSelectivo.getContentPane().setLayout(MenuSelectivoLayout);
        MenuSelectivoLayout.setHorizontalGroup(
            MenuSelectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSelectivoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(tmaestrocreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(talumnocreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        MenuSelectivoLayout.setVerticalGroup(
            MenuSelectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSelectivoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MenuSelectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmaestrocreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talumnocreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Ingresar al Sistema");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Crear Usuarios");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Usuario:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(341, 341, 341))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxClaseAporbadaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxClaseAporbadaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxClaseAporbadaAActionPerformed

    private void TxValorUnidAsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxValorUnidAsignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxValorUnidAsignActionPerformed

    private void TxAulaAsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxAulaAsignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxAulaAsignActionPerformed

    private void btagregar2AlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btagregar2AlumnoMouseClicked
        // TODO add your handling code here:
        //agregar
       Dba db = new Dba("./BaseDatosRegistro.mdb");
        db.conectar();
        try {
            int c, indice, claseprob;
            String n, contra, carrera, becado,descuento, lista;
            
            
            n = TxNombreA.getText();
            c = Integer.parseInt(TxNumCuentaA.getText());
            contra = TxContraseñaA.getText();
            carrera = TxCarreraA.getText();
            becado = TxBecadoA.getText();
            descuento = TDescuentoA.getText();
            indice = Integer.parseInt(TxIndiceA.getText());
            claseprob = Integer.parseInt(TxClaseAporbadaA.getText());
            lista = TListaClaseA.getText();
            
            
            
            db.query.execute("INSERT INTO Alumnos"
                    + " (Nombre,Numero_cuenta,Contrasena,Carrera,Becado,Indice,Descuento,CantAprob,ListA)"
                    + " VALUES ('" + n + "', '" + c + "', '" + contra + "', '" + carrera + "', '" + becado + "', '" + indice + "', '" + descuento + "', '" + claseprob + "', '" + lista +  "')");
            db.commit();
            
            TxNombreA.setText("");
            TxNumCuentaA.setText("");
            TxContraseñaA.setText("");
            TxCarreraA.setText("");
            TxBecadoA.setText("");
            TDescuentoA.setText("");
            TxIndiceA.setText("");
            TxClaseAporbadaA.setText("");
            TListaClaseA.setText("");
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
 
        
        
    }//GEN-LAST:event_btagregar2AlumnoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     //listar        
     Dba db = new Dba("./BaseDatosRegistro.mdb");
        db.conectar();
        try {
            db.query.execute("select * from Alumnos where Numero_cuenta= "+ jTextField1.getText() +" and Contrasena="+ jTextField2.getText() +"");
            ResultSet rs = db.query.getResultSet();
            if (rs.next()) {
               
            }
            
             db.query.execute("select * from Maestros where Numero_cuenta= "+ jTextField1.getText() +" and Contrasena="+ jTextField2.getText() +"");
            ResultSet rs2 = db.query.getResultSet();
            if (rs2.next()) {
             jAsignaturas.pack();
             jAsignaturas.setLocationRelativeTo(this);
             jAsignaturas.setModal(true);
             jAsignaturas.setVisible(true);
            }
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void btagregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btagregar1MouseClicked
        // TODO add your handling code here:
               // TODO add your handling code here:
        //agregar
       Dba db = new Dba("./BaseDatosRegistro.mdb");
        db.conectar();
        try {
            int c, valorund,aula,edifasugn,cantalumn,tprec;
            String n,  seccion, horario, docente, modalidad, tdiasImpart;
            
            
            
            n = TxNombreAsign.getText();
            c = Integer.parseInt(TxNumCuentaAsign.getText());
            seccion = TxNumSeccionAsign.getText();
            horario =  TxHorarioAsign.getText();
            docente = TxDocenteAsign.getText();
            valorund = Integer.parseInt(TxValorUnidAsign.getText());
            aula =  Integer.parseInt(TxAulaAsign.getText());
            edifasugn =  Integer.parseInt(TxEdificioAsign.getText());
            cantalumn = Integer.parseInt(TCantalumnoAsign.getText());
            modalidad = TModalidadAsign.getText();
            tdiasImpart = TDiasImparteAsign.getText();
            tprec = Integer.parseInt(TPrecioAsign.getText());
            
            
            
            
            db.query.execute("INSERT INTO Asignaturas"
                    + " (Nombre,cod_asig,cod_sec,horario,docente,cant_vlunt,aulaedificio,Cantalumn,Modalidad,DíasImparte,precio)"
                    + " VALUES ('" + n + "', '" + c + "', '" + seccion + "', '" + horario + "', '" + docente + "', '" + valorund + "', '" + aula + "', '" + edifasugn + "', '" + cantalumn + "', '" + modalidad + "', '" + tdiasImpart + "', '" + tprec +  "')");
            db.commit();
            
            TxNombreAsign.setText("");
            TxNumCuentaAsign.setText("");
            TxNumSeccionAsign.setText("");
            TxHorarioAsign.setText("");
            TxDocenteAsign.setText("");
            TxValorUnidAsign.setText("");
            TxAulaAsign.setText("");
            TxEdificioAsign.setText("");
            TCantalumnoAsign.setText("");
            TModalidadAsign.setText("");
            TDiasImparteAsign.setText("");
            TPrecioAsign.setText("");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
 
    }//GEN-LAST:event_btagregar1MouseClicked

    private void TPrecioAsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPrecioAsignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPrecioAsignActionPerformed

    private void tmaestrocreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmaestrocreacionMouseClicked
        // TODO add your handling code here:
        jmaestros.pack();
        jmaestros.setLocationRelativeTo(this);
        jmaestros.setModal(true);
        jmaestros.setVisible(true);
    }//GEN-LAST:event_tmaestrocreacionMouseClicked

    private void talumnocreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_talumnocreacionMouseClicked
        // TODO add your handling code here:
         jalumnos.pack();
        jalumnos.setLocationRelativeTo(this);
        jalumnos.setModal(true);
        jalumnos.setVisible(true);
    }//GEN-LAST:event_talumnocreacionMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        MenuSelectivo.pack();
        MenuSelectivo.setLocationRelativeTo(this);
        MenuSelectivo.setModal(true);
        MenuSelectivo.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void btagregarMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btagregarMaestroMouseClicked
             // TODO add your handling code here:
        //agregar
       Dba db = new Dba("./BaseDatosRegistro.mdb");
        db.conectar();
        try {
            int c;
            String n, contra, lista, nacionalidad, titulo;
           
            
            n = TxNombreM.getText();
            c = Integer.parseInt(TxNumCuentaM.getText());
            contra = TxContraseñaM.getText();
            nacionalidad = TxNacionalidadM.getText();
            titulo = TxTituloM.getText();
            lista = TListaClases.getText();
            
            
            
            db.query.execute("INSERT INTO Maestros"
                    + " (Nombre,Numero_cuenta,Contrasena,nacionalidad,titulo,lista)"
                    + " VALUES ('" + n + "', '" + c + "', '" + contra + "', '" + nacionalidad + "', '" + titulo + "', '" + lista + "')");
            db.commit();
            
            TxNombreM.setText("");
            TxNumCuentaM.setText("");
            TxContraseñaM.setText("");
            TxNacionalidadM.setText("");
            TxTituloM.setText("");
            TListaClases.setText("");
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
 
        
        
    }//GEN-LAST:event_btagregarMaestroMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ethereum_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ethereum_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ethereum_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ethereum_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ethereum_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog MenuSelectivo;
    private javax.swing.JTextField TCantalumnoAsign;
    private javax.swing.JTextField TDescuentoA;
    private javax.swing.JTextField TDiasImparteAsign;
    private javax.swing.JTextField TListaClaseA;
    private javax.swing.JTextField TListaClases;
    private javax.swing.JTextField TModalidadAsign;
    private javax.swing.JTextField TPrecioAsign;
    private javax.swing.JTextField TxAulaAsign;
    private javax.swing.JTextField TxBecadoA;
    private javax.swing.JTextField TxCarreraA;
    private javax.swing.JTextField TxClaseAporbadaA;
    private javax.swing.JTextField TxContraseñaA;
    private javax.swing.JTextField TxContraseñaM;
    private javax.swing.JTextField TxDocenteAsign;
    private javax.swing.JTextField TxEdificioAsign;
    private javax.swing.JTextField TxHorarioAsign;
    private javax.swing.JTextField TxIndiceA;
    private javax.swing.JTextField TxNacionalidadM;
    private javax.swing.JTextField TxNombreA;
    private javax.swing.JTextField TxNombreAsign;
    private javax.swing.JTextField TxNombreM;
    private javax.swing.JTextField TxNumCuentaA;
    private javax.swing.JTextField TxNumCuentaAsign;
    private javax.swing.JTextField TxNumCuentaM;
    private javax.swing.JTextField TxNumSeccionAsign;
    private javax.swing.JTextField TxTituloM;
    private javax.swing.JTextField TxValorUnidAsign;
    private javax.swing.JButton btagregar1;
    private javax.swing.JButton btagregar2Alumno;
    private javax.swing.JButton btagregarMaestro;
    private javax.swing.JDialog jAsignaturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDialog jalumnos;
    private javax.swing.JDialog jmaestros;
    private javax.swing.JButton talumnocreacion;
    private javax.swing.JButton tmaestrocreacion;
    // End of variables declaration//GEN-END:variables
}
