/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ethereum_sistema;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Simulador extends javax.swing.JFrame {

    private JComboBox<String> asignaturasComboBox;
    private JCheckBox[] asignaturasCheckboxes;
//     private JComboBox<String> ASIGNATURAS; // Agrega esta línea
    private JTextField descuentoTextField;
    private JButton calcularButton;
    private JLabel totalCostoLabel;
    private JLabel totalDescuentoLabel;
    private JLabel proyeccionLabel;
    private JLabel cuotaMensualLabel;
    private DefaultTableModel modeloTabla;

    public Simulador() {
        initComponents();
        setTitle("Simulación de Inversión");

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        modeloTabla = new DefaultTableModel();
        modeloTabla = new DefaultTableModel();
        TABLA = new JTable(modeloTabla);
        modeloTabla.addColumn("Concepto");
        modeloTabla.addColumn("Valor");
        asignaturasComboBox = new JComboBox<>();
         ASIGNATURAS = new JComboBox<>(); // Inicializa la variable

        // Crear un modelo de ComboBox personalizado
        // Crear un modelo de ComboBox personalizado
//        DefaultComboBoxModel<Asignatura> comboBoxModel = new DefaultComboBoxModel<>();
// Crear las instancias de las asignaturas
        Asignatura asignatura1 = new Asignatura("ASG001", "Asignatura 1", 0.20, 0.1);
        Asignatura asignatura2 = new Asignatura("ASG002", "Asignatura 2", 0.25, 0.2);
        // Agregar los elementos al ComboBox
        ASIGNATURAS.addItem(asignatura1.getNombre());
        ASIGNATURAS.addItem(asignatura2.getNombre());
//
//// Establecer el modelo en el JComboBox
//        JComboBox<String> DESCUENTO = new JComboBox<>();
//        Asignatura asignaturaSeleccionada = (Asignatura) ASIGNATURAS.getSelectedItem();
//        DESCUENTO.addItem(String.format("%.0f%%", asignaturaSeleccionada.getDescuento() * 100));
//    }

//    private void calcular() {
//        double totalCostoSinDescuento = 0.0;
//        double totalDescuento = 0.0;
//        double totalProyeccion = 0.0;
//        double cuotaMensual = 0.0;
//
//        Asignatura[] asignaturas = {
//            new Asignatura("ASG001", "Asignatura 1", 0.20, 0.1),
//            new Asignatura("ASG002", "Asignatura 2", 0.20, 0.1),
//            new Asignatura("ASG003", "Asignatura 3", 0.036, 0.0)
//        };
//
//        for (int i = 0; i < asignaturasCheckboxes.length; i++) {
//            if (asignaturasCheckboxes[i].isSelected()) {
//                totalCostoSinDescuento += asignaturas[i].getCosto();
//                totalDescuento += asignaturas[i].getCosto() * asignaturas[i].getDescuento();
//            }
//        }
//
//        totalProyeccion = totalCostoSinDescuento - totalDescuento;
//        cuotaMensual = totalProyeccion / 3;
//
//        modeloTabla.setRowCount(0);
//
//        modeloTabla.addRow(new Object[]{"Total sin descuento", String.format("%.2f ETH / %.2f LPS", totalCostoSinDescuento, convertirEthALps(totalCostoSinDescuento))});
//        modeloTabla.addRow(new Object[]{"Total con descuento", String.format("%.2f ETH / %.2f LPS", totalDescuento, convertirEthALps(totalDescuento))});
//        modeloTabla.addRow(new Object[]{"Total proyección", String.format("%.2f ETH / %.2f LPS", totalProyeccion, convertirEthALps(totalProyeccion))});
//        modeloTabla.addRow(new Object[]{"Cuota mensual", String.format("%.2f ETH / %.2f LPS", cuotaMensual, convertirEthALps(cuotaMensual))});
//    }
//
//    private double convertirEthALps(double eth) {
//        // Método para convertir ETH a LPS (Lempiras)
//        return eth * 1000; // Solo es un ejemplo, debes proporcionar la tasa de conversión real
//
//    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ASIGNATURAS = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        DESCUENTO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        COSTO_ASIGNATURA = new javax.swing.JComboBox<>();
        CALCULAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULACION");

        jLabel1.setText("Asigaturas Disponibles: ");

        ASIGNATURAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"ASG001\", \"Asignatura 1\", 0.20, 10%", "\"ASG002\", \"Asignatura 2\", 0.25, 20%" }));

        jLabel2.setText(" Descuento (%):  ");

        DESCUENTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%" }));

        jLabel3.setText("Costo de la Asignatura:");

        COSTO_ASIGNATURA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.020 ETH", "0.036 ETH" }));

        CALCULAR.setText("Calcular");
        CALCULAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CALCULARMouseClicked(evt);
            }
        });

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Total Sin Descuento", "Con Descuento", "Cuota Mensual"
            }
        ));
        jScrollPane1.setViewportView(TABLA);

        jLabel4.setText("Proyeccion A Pagar: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ASIGNATURAS, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(COSTO_ASIGNATURA, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(DESCUENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ASIGNATURAS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(COSTO_ASIGNATURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DESCUENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CALCULARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALCULARMouseClicked
        // TODO add your handling code here:
    //    calcular();
    }//GEN-LAST:event_CALCULARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ASIGNATURAS;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JComboBox<String> COSTO_ASIGNATURA;
    private javax.swing.JComboBox<String> DESCUENTO;
    private javax.swing.JTable TABLA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
